### PR TITLE
Japanese Translation

### PR DESCRIPTION
**Pull request by mas178**
It's my first pr, please let me know if there are any problems.

### CODE REVIEW

**Comment by shentschel** [comment]
Hi Masaaki,

this pull reuqest looks good. :+1:  I only have a question regarding some items which are not or only partly translated. 

The Keys of the items are:

* CURRENT_GROUPS
* ACTION
* RESTRICTION_NOTICE
* TASK_LIST_LOADING_FAILURE

Have you missed them or is there no translation for these items?

Cheers

Stefan :)

**Comment by mas178** [comment]
Hi Stefan,

Thank you for your review. They are mistakes and fixed them.

Masaaki

**Comment by shentschel** [comment]
Hi Masaaki,

yesterday @SebastianStamm added a new field to the english translation. Maybe you want to translate it with this pull request too. The Item is:

* "NEW_TASK_TENANT_ID": "Tenant Id"

If you do this, the translation would be completely in sync with our current english translation.

Cheers,

Stefan :)

**Comment by mas178** [comment]
I added NEW_TASK_TENANT_ID.
BTW the new multi-tenancy function is very cool! 👍

**Comment by shentschel** [comment]
Hi Masaaki,

I merged your pull request :) 

どうもありがとうございました :+1: 

Cheers,

Stefan

**Pull request closed without merging**
